/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Signup
         * @description Register a new user.
         *
         *     - **username**: Unique username
         *     - **email**: Valid email address
         *     - **password**: Password (will be hashed)
         */
        post: operations["signup_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Login and get JWT access token.
         *
         *     Uses OAuth2 password flow - send username and password as form data.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Google Auth
         * @description Authenticate with Google SSO.
         *
         *     Verifies the Google ID token, finds or creates the user, and returns a JWT.
         */
        post: operations["google_auth_auth_google_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Get current user's profile.
         */
        get: operations["get_me_auth_me_get"];
        /**
         * Update Me
         * @description Update current user's profile.
         */
        put: operations["update_me_auth_me_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leagues/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create New League
         * @description Create a new league.
         *
         *     The current user becomes the owner and is automatically added as a member.
         *     A unique 6-character invite code is generated.
         */
        post: operations["create_new_league_leagues__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leagues/preview/{invite_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview League
         * @description Public endpoint — returns basic league info for an invite code.
         *     No auth required so the join page can show the league name before login.
         */
        get: operations["preview_league_leagues_preview__invite_code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leagues/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join Existing League
         * @description Join a league using an invite code.
         */
        post: operations["join_existing_league_leagues_join_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leagues/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get My Leagues
         * @description Get all leagues the current user is a member of.
         */
        get: operations["get_my_leagues_leagues_my_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leagues/{league_id}/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Leaderboard
         * @description Get the leaderboard for a specific league.
         *
         *     Only members of the league can view the leaderboard.
         */
        get: operations["get_leaderboard_leagues__league_id__leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leagues/{league_id}/matches/{match_id}/predictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get League Match Predictions
         * @description Get all league members' predictions for a locked match.
         *     Only accessible after the match's prediction window has closed (start_time has passed).
         */
        get: operations["get_league_match_predictions_leagues__league_id__matches__match_id__predictions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leagues/{league_id}/matches/{match_id}/verdict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Match Verdict Endpoint
         * @description The Match Verdict for a (league, match) pair — used as the page hero on
         *     /leagues/[id]/match/[id]. Returns 404 if the match isn't completed/scored
         *     or no league member predicted it.
         */
        get: operations["get_match_verdict_endpoint_leagues__league_id__matches__match_id__verdict_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Matches
         * @description List matches.
         *
         *     By default returns only upcoming (scheduled) matches.
         *     Use `include_completed=true` to include completed matches.
         *     Optionally filter by `tournament_id`.
         */
        get: operations["list_matches_matches__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{match_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Match Detail
         * @description Get detailed match info including results for completed matches.
         */
        get: operations["get_match_detail_matches__match_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{match_id}/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Players For Match
         * @description Get all players from both teams in a match.
         *
         *     Used for populating dropdowns in the prediction form.
         */
        get: operations["get_players_for_match_matches__match_id__players_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/predictions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Prediction
         * @description Submit a prediction for a match.
         *
         *     Predictions can only be submitted before the match starts (UTC).
         *     If a prediction already exists for this match, it will be updated.
         *
         *     **Scoring:**
         *     - Winner: +10 pts
         *     - Most Runs (Team 1): +20 pts
         *     - Most Runs (Team 2): +20 pts
         *     - Most Wickets (Team 1): +20 pts
         *     - Most Wickets (Team 2): +20 pts
         *     - Player of Match: +50 pts
         *     - Max total: 140 pts
         */
        post: operations["submit_prediction_predictions__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/predictions/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get My Predictions
         * @description Get all predictions made by the current user (raw IDs).
         */
        get: operations["get_my_predictions_predictions_my_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/predictions/my/detailed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get My Predictions Detailed
         * @description Get all predictions with match context, player names, and actual results.
         */
        get: operations["get_my_predictions_detailed_predictions_my_detailed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/matches/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Match
         * @description Create a new match (Admin only).
         *
         *     Requires admin privileges to create matches.
         */
        post: operations["create_match_admin_matches__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/matches/{match_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Match Result
         * @description Set match results and trigger score calculation (Admin only).
         *
         *     This endpoint:
         *     1. Updates the match with results
         *     2. Sets match status to COMPLETED
         *     3. Triggers automatic score calculation for all predictions
         *
         *     Note: In a production app, this should be restricted to admin users.
         */
        post: operations["set_match_result_admin_matches__match_id__result_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List All Matches
         * @description List all matches with their status (Admin only).
         */
        get: operations["list_all_matches_admin_matches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/matches/{match_id}/predictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Match Predictions
         * @description Get all predictions for a specific match (Admin only).
         */
        get: operations["get_match_predictions_admin_matches__match_id__predictions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/matches/{match_id}/squad": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Match Squad
         * @description Get full squad for both teams in a match (Admin only). Ignores lineup filtering.
         */
        get: operations["get_match_squad_admin_matches__match_id__squad_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/matches/{match_id}/lineup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Match Lineup
         * @description Get current lineup for a match (Admin only).
         */
        get: operations["get_match_lineup_admin_matches__match_id__lineup_get"];
        put?: never;
        /**
         * Set Match Lineup
         * @description Set playing XI for a match (Admin only).
         *
         *     Accepts 22 player IDs (11 per team). Validates all players belong to
         *     one of the two match teams and that exactly 11 are selected per team.
         */
        post: operations["set_match_lineup_admin_matches__match_id__lineup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/matches/{match_id}/previous-lineup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Previous Lineup
         * @description Return player IDs from the most recent prior lineup for each team in this match.
         *     Used to pre-fill the lineup form so admins only need to make small adjustments.
         */
        get: operations["get_previous_lineup_admin_matches__match_id__previous_lineup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/matches/{match_id}/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Link Match To Cricapi
         * @description Link a match to a CricAPI external_match_id and validate the ID.
         */
        post: operations["link_match_to_cricapi_admin_matches__match_id__link_post"];
        /**
         * Unlink Match From Cricapi
         * @description Remove CricAPI link from a match and reset sync state.
         */
        delete: operations["unlink_match_from_cricapi_admin_matches__match_id__link_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/matches/{match_id}/sync-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Match Sync Status
         * @description Get current CricAPI sync state + live preview for a match.
         */
        get: operations["get_match_sync_status_admin_matches__match_id__sync_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/matches/{match_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Manual Sync
         * @description Force an immediate sync cycle for a specific match.
         */
        post: operations["trigger_manual_sync_admin_matches__match_id__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/matches/{match_id}/player-mapping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Player Mapping
         * @description Show resolved and unresolved CricAPI player name mappings for a match.
         */
        get: operations["get_player_mapping_admin_matches__match_id__player_mapping_get"];
        put?: never;
        /**
         * Save Player Mapping
         * @description Save cricapi_player_id on Player records (one-time bootstrap per season).
         */
        post: operations["save_player_mapping_admin_matches__match_id__player_mapping_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/series/{series_id}/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Series Matches
         * @description List CricAPI matches in a series (for finding the right external_match_id).
         */
        get: operations["list_series_matches_admin_series__series_id__matches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tournaments/{tournament_id}/picks-window": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Set Picks Window
         * @description Set the tournament picks window state (Admin only).
         */
        patch: operations["set_picks_window_admin_tournaments__tournament_id__picks_window_patch"];
        trace?: never;
    };
    "/admin/tournaments/{tournament_id}/picks-result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Picks Result
         * @description Set tournament Top 4 + player results and trigger picks scoring (Admin only).
         */
        post: operations["set_picks_result_admin_tournaments__tournament_id__picks_result_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/vapid-public-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Vapid Public Key
         * @description Return the VAPID public key for the frontend to use when subscribing.
         */
        get: operations["get_vapid_public_key_notifications_vapid_public_key_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/push/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Subscribe
         * @description Save a push subscription for the current user.
         */
        post: operations["subscribe_notifications_push_subscribe_post"];
        /**
         * Unsubscribe
         * @description Remove a push subscription.
         */
        delete: operations["unsubscribe_notifications_push_subscribe_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dugout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dugout */
        get: operations["get_dugout_dugout__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dugout/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dismiss Dugout Event */
        post: operations["dismiss_dugout_event_dugout_dismiss_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tournaments
         * @description List all tournaments.
         */
        get: operations["list_tournaments_tournaments__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments/{tournament_id}/picks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get My Picks
         * @description Get the current user's tournament picks and window state.
         */
        get: operations["get_my_picks_tournaments__tournament_id__picks_get"];
        put?: never;
        /**
         * Submit Picks
         * @description Submit or update tournament picks (only when window is open or open2).
         */
        post: operations["submit_picks_tournaments__tournament_id__picks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments/{tournament_id}/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Teams
         * @description List all teams participating in the tournament.
         */
        get: operations["list_teams_tournaments__tournament_id__teams_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments/{tournament_id}/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Players
         * @description List all players in the tournament for pick dropdowns.
         */
        get: operations["list_players_tournaments__tournament_id__players_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Health check endpoint.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Health check endpoint.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_login_auth_login_post */
        Body_login_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /**
         * BulkPlayerMappingRequest
         * @description Save cricapi_player_id on one or more Player records.
         */
        BulkPlayerMappingRequest: {
            /** Mappings */
            mappings: components["schemas"]["PlayerMappingItem"][];
        };
        /** DugoutDismissRequest */
        DugoutDismissRequest: {
            type: components["schemas"]["DugoutEventType"];
            /** League Id */
            league_id: number;
            /** Match Id */
            match_id?: number | null;
            /** Subject Username */
            subject_username: string;
        };
        /** DugoutEvent */
        DugoutEvent: {
            type: components["schemas"]["DugoutEventType"];
            /** League Name */
            league_name: string;
            /** League Id */
            league_id: number;
            /** Match Id */
            match_id?: number | null;
            /** Username */
            username: string;
            /** Display Name */
            display_name?: string | null;
            /**
             * Is Me
             * @default false
             */
            is_me: boolean;
            /** Streak Count */
            streak_count?: number | null;
            /** Rank */
            rank?: number | null;
            /** Rank Delta */
            rank_delta?: number | null;
            /** Agreement Count */
            agreement_count?: number | null;
            /** Team Short Name */
            team_short_name?: string | null;
            /** Winners */
            winners?: components["schemas"]["VerdictWinner"][] | null;
            /** Runners Up */
            runners_up?: components["schemas"]["VerdictRunner"][] | null;
            /** Pom Player Name */
            pom_player_name?: string | null;
            /** Winning Team Short */
            winning_team_short?: string | null;
            /** Losing Team Short */
            losing_team_short?: string | null;
            /** Match Label */
            match_label?: string | null;
            /** Top Score */
            top_score?: number | null;
            /** Runner Up Score */
            runner_up_score?: number | null;
        };
        /**
         * DugoutEventType
         * @enum {string}
         */
        DugoutEventType: "contrarian" | "agreement" | "streak" | "rank_shift" | "match_verdict";
        /**
         * FriendPrediction
         * @description A league member's prediction for a match, shown in the league activity feed.
         */
        FriendPrediction: {
            /** Username */
            username: string;
            /** Display Name */
            display_name?: string | null;
            /** Is Me */
            is_me: boolean;
            /** Points Earned */
            points_earned: number;
            /** Is Processed */
            is_processed: boolean;
            predicted_winner: components["schemas"]["TeamResponse"];
            predicted_most_runs_team1_player: components["schemas"]["PlayerResponse"];
            predicted_most_runs_team2_player: components["schemas"]["PlayerResponse"];
            predicted_most_wickets_team1_player: components["schemas"]["PlayerResponse"];
            predicted_most_wickets_team2_player: components["schemas"]["PlayerResponse"];
            predicted_pom_player: components["schemas"]["PlayerResponse"];
            actual_winner?: components["schemas"]["TeamResponse"] | null;
            actual_most_runs_team1_player?: components["schemas"]["PlayerResponse"] | null;
            actual_most_runs_team2_player?: components["schemas"]["PlayerResponse"] | null;
            actual_most_wickets_team1_player?: components["schemas"]["PlayerResponse"] | null;
            actual_most_wickets_team2_player?: components["schemas"]["PlayerResponse"] | null;
            actual_pom_player?: components["schemas"]["PlayerResponse"] | null;
        };
        /**
         * GoogleAuthRequest
         * @description Schema for Google SSO login.
         */
        GoogleAuthRequest: {
            /** Credential */
            credential: string;
        };
        /**
         * GoogleAuthResponse
         * @description Schema for Google SSO response (JWT + username for frontend login).
         */
        GoogleAuthResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Username */
            username: string;
            /** Display Name */
            display_name?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LeaderboardEntry
         * @description Schema for a leaderboard entry.
         */
        LeaderboardEntry: {
            /** User Id */
            user_id: number;
            /** Username */
            username: string;
            /** Display Name */
            display_name?: string | null;
            /** Total Points */
            total_points: number;
            /** Rank */
            rank: number;
            /** Rank Delta */
            rank_delta?: number | null;
        };
        /**
         * LeaderboardResponse
         * @description Schema for leaderboard response.
         */
        LeaderboardResponse: {
            /** League Id */
            league_id: number;
            /** League Name */
            league_name: string;
            /** Entries */
            entries: components["schemas"]["LeaderboardEntry"][];
        };
        /**
         * LeagueCreate
         * @description Schema for creating a new league.
         */
        LeagueCreate: {
            /** Name */
            name: string;
            /**
             * Sport
             * @default cricket
             */
            sport: string;
        };
        /**
         * LeagueJoin
         * @description Schema for joining a league.
         */
        LeagueJoin: {
            /** Invite Code */
            invite_code: string;
        };
        /**
         * LeagueResponse
         * @description Schema for league response.
         */
        LeagueResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Invite Code */
            invite_code: string;
            /** Owner Id */
            owner_id: number;
            /**
             * Sport
             * @default cricket
             */
            sport: string;
        };
        /**
         * LinkMatchRequest
         * @description Link a match to a CricAPI external_match_id.
         */
        LinkMatchRequest: {
            /** External Match Id */
            external_match_id: string;
        };
        /**
         * MatchCreate
         * @description Schema for creating a match.
         */
        MatchCreate: {
            /** Tournament Id */
            tournament_id: number;
            /** Team 1 Id */
            team_1_id: number;
            /** Team 2 Id */
            team_2_id: number;
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
        };
        /**
         * MatchDetailResponse
         * @description Schema for match detail with results.
         */
        MatchDetailResponse: {
            /** Id */
            id: number;
            /** Tournament Id */
            tournament_id: number;
            team_1: components["schemas"]["TeamResponse"];
            team_2: components["schemas"]["TeamResponse"];
            /** Start Time */
            start_time: string;
            /** Status */
            status: string;
            winner?: components["schemas"]["TeamResponse"] | null;
            most_runs_team1_player?: components["schemas"]["PlayerResponse"] | null;
            most_runs_team2_player?: components["schemas"]["PlayerResponse"] | null;
            most_wickets_team1_player?: components["schemas"]["PlayerResponse"] | null;
            most_wickets_team2_player?: components["schemas"]["PlayerResponse"] | null;
            pom_player?: components["schemas"]["PlayerResponse"] | null;
        };
        /**
         * MatchPlayersResponse
         * @description Schema for match players response.
         */
        MatchPlayersResponse: {
            /** Match Id */
            match_id: number;
            team_1: components["schemas"]["TeamResponse"];
            team_2: components["schemas"]["TeamResponse"];
            /** Team 1 Players */
            team_1_players: components["schemas"]["PlayerResponse"][];
            /** Team 2 Players */
            team_2_players: components["schemas"]["PlayerResponse"][];
            /** Team 1 Form */
            team_1_form?: components["schemas"]["TeamFormEntryResponse"][];
            /** Team 2 Form */
            team_2_form?: components["schemas"]["TeamFormEntryResponse"][];
            /**
             * Lineup Announced
             * @default false
             */
            lineup_announced: boolean;
            /** Start Time */
            start_time: string;
        };
        /**
         * MatchResponse
         * @description Schema for match response.
         */
        MatchResponse: {
            /** Id */
            id: number;
            /** Tournament Id */
            tournament_id: number;
            team_1: components["schemas"]["TeamResponse"];
            team_2: components["schemas"]["TeamResponse"];
            /** Start Time */
            start_time: string;
            /** Status */
            status: string;
            /**
             * Lineup Announced
             * @default false
             */
            lineup_announced: boolean;
        };
        /**
         * MatchResultCreate
         * @description Schema for setting match results.
         */
        MatchResultCreate: {
            /** Result Winner Id */
            result_winner_id: number;
            /** Result Most Runs Team1 Player Id */
            result_most_runs_team1_player_id: number;
            /** Result Most Runs Team2 Player Id */
            result_most_runs_team2_player_id: number;
            /** Result Most Wickets Team1 Player Id */
            result_most_wickets_team1_player_id: number;
            /** Result Most Wickets Team2 Player Id */
            result_most_wickets_team2_player_id: number;
            /** Result Pom Player Id */
            result_pom_player_id: number;
        };
        /** PlayerMappingItem */
        PlayerMappingItem: {
            /** Provider Id */
            provider_id: string;
            /** Player Id */
            player_id: number;
        };
        /** PlayerPickOption */
        PlayerPickOption: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Team Id */
            team_id: number;
            /** Team Name */
            team_name?: string | null;
        };
        /**
         * PlayerResponse
         * @description Schema for player response.
         */
        PlayerResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Team Id */
            team_id: number;
            /** Role */
            role: string;
            /**
             * Played Last Match
             * @default false
             */
            played_last_match: boolean;
        };
        /**
         * PredictionCreate
         * @description Schema for creating a prediction.
         */
        PredictionCreate: {
            /** Match Id */
            match_id: number;
            /** Predicted Winner Id */
            predicted_winner_id: number;
            /** Predicted Most Runs Team1 Player Id */
            predicted_most_runs_team1_player_id: number;
            /** Predicted Most Runs Team2 Player Id */
            predicted_most_runs_team2_player_id: number;
            /** Predicted Most Wickets Team1 Player Id */
            predicted_most_wickets_team1_player_id: number;
            /** Predicted Most Wickets Team2 Player Id */
            predicted_most_wickets_team2_player_id: number;
            /** Predicted Pom Player Id */
            predicted_pom_player_id: number;
        };
        /**
         * PredictionDetailResponse
         * @description Enriched prediction with match context and player names.
         */
        PredictionDetailResponse: {
            /** Id */
            id: number;
            /** Match Id */
            match_id: number;
            /** Points Earned */
            points_earned: number;
            /** Is Processed */
            is_processed: boolean;
            team_1: components["schemas"]["TeamResponse"];
            team_2: components["schemas"]["TeamResponse"];
            /** Start Time */
            start_time: string;
            /** Status */
            status: string;
            predicted_winner: components["schemas"]["TeamResponse"];
            predicted_most_runs_team1_player: components["schemas"]["PlayerResponse"];
            predicted_most_runs_team2_player: components["schemas"]["PlayerResponse"];
            predicted_most_wickets_team1_player: components["schemas"]["PlayerResponse"];
            predicted_most_wickets_team2_player: components["schemas"]["PlayerResponse"];
            predicted_pom_player: components["schemas"]["PlayerResponse"];
            actual_winner?: components["schemas"]["TeamResponse"] | null;
            actual_most_runs_team1_player?: components["schemas"]["PlayerResponse"] | null;
            actual_most_runs_team2_player?: components["schemas"]["PlayerResponse"] | null;
            actual_most_wickets_team1_player?: components["schemas"]["PlayerResponse"] | null;
            actual_most_wickets_team2_player?: components["schemas"]["PlayerResponse"] | null;
            actual_pom_player?: components["schemas"]["PlayerResponse"] | null;
        };
        /**
         * PredictionResponse
         * @description Schema for prediction response.
         */
        PredictionResponse: {
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
            /** Match Id */
            match_id: number;
            /** Predicted Winner Id */
            predicted_winner_id: number;
            /** Predicted Most Runs Team1 Player Id */
            predicted_most_runs_team1_player_id: number;
            /** Predicted Most Runs Team2 Player Id */
            predicted_most_runs_team2_player_id: number;
            /** Predicted Most Wickets Team1 Player Id */
            predicted_most_wickets_team1_player_id: number;
            /** Predicted Most Wickets Team2 Player Id */
            predicted_most_wickets_team2_player_id: number;
            /** Predicted Pom Player Id */
            predicted_pom_player_id: number;
            /** Points Earned */
            points_earned: number;
            /** Is Processed */
            is_processed: boolean;
        };
        /**
         * ProfileUpdate
         * @description Schema for updating user profile.
         */
        ProfileUpdate: {
            /** Display Name */
            display_name: string;
        };
        /** PushSubscribeRequest */
        PushSubscribeRequest: {
            /** Endpoint */
            endpoint: string;
            /** Auth */
            auth: string;
            /** P256Dh */
            p256dh: string;
        };
        /**
         * SetLineupRequest
         * @description Schema for setting match playing XI.
         */
        SetLineupRequest: {
            /** Player Ids */
            player_ids: number[];
        };
        /** SetPicksResultRequest */
        SetPicksResultRequest: {
            /** Result Top4 Team Ids */
            result_top4_team_ids: number[];
            /** Result Best Batsman Player Id */
            result_best_batsman_player_id: number;
            /** Result Best Bowler Player Id */
            result_best_bowler_player_id: number;
        };
        /** SetPicksWindowRequest */
        SetPicksWindowRequest: {
            /** Window */
            window: string;
        };
        /** SyncStatusResponse */
        SyncStatusResponse: {
            /** Match Id */
            match_id: number;
            /** External Match Id */
            external_match_id: string | null;
            /** Sync State */
            sync_state: string;
            /** Last Synced At */
            last_synced_at: string | null;
            /** Sync Error */
            sync_error: string | null;
            /** Cricapi Preview */
            cricapi_preview?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * TeamFormEntryResponse
         * @description Schema for a team's recent form entry.
         */
        TeamFormEntryResponse: {
            /** Match Id */
            match_id: number;
            /** Opponent Short Name */
            opponent_short_name: string;
            /** Result */
            result: string;
            /** Start Time */
            start_time: string;
        };
        /** TeamPickOption */
        TeamPickOption: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Short Name */
            short_name: string;
            /** Logo Url */
            logo_url?: string | null;
        };
        /**
         * TeamResponse
         * @description Schema for team response.
         */
        TeamResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Short Name */
            short_name: string;
            /** Logo Url */
            logo_url?: string | null;
        };
        /**
         * Token
         * @description Schema for JWT token response.
         */
        Token: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Display Name */
            display_name?: string | null;
        };
        /** TournamentPicksResponse */
        TournamentPicksResponse: {
            /** Tournament Id */
            tournament_id: number;
            /** Tournament Name */
            tournament_name: string;
            /** Picks Window */
            picks_window: string;
            /** Top4 Team Ids */
            top4_team_ids: (number | null)[];
            /** Best Batsman Player Id */
            best_batsman_player_id: number | null;
            /** Best Bowler Player Id */
            best_bowler_player_id: number | null;
            /** Points Earned */
            points_earned: number;
            /** Is Window2 */
            is_window2: boolean;
            /** Is Processed */
            is_processed: boolean;
        };
        /** TournamentPicksSubmit */
        TournamentPicksSubmit: {
            /** Top4 Team Ids */
            top4_team_ids: number[];
            /** Best Batsman Player Id */
            best_batsman_player_id?: number | null;
            /** Best Bowler Player Id */
            best_bowler_player_id?: number | null;
        };
        /**
         * UserCreate
         * @description Schema for user registration.
         */
        UserCreate: {
            /** Username */
            username: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * UserResponse
         * @description Schema for user response (excludes password).
         */
        UserResponse: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VerdictHits */
        VerdictHits: {
            /** Winner */
            winner: boolean;
            /** Runs T1 */
            runs_t1: boolean;
            /** Runs T2 */
            runs_t2: boolean;
            /** Wkts T1 */
            wkts_t1: boolean;
            /** Wkts T2 */
            wkts_t2: boolean;
            /** Pom */
            pom: boolean;
        };
        /** VerdictRunner */
        VerdictRunner: {
            /** User Id */
            user_id: number;
            /** Username */
            username: string;
            /** Display Name */
            display_name?: string | null;
            /** Points Earned */
            points_earned: number;
            /** Prev Rank */
            prev_rank?: number | null;
            /** New Rank */
            new_rank: number;
        };
        /** VerdictWinner */
        VerdictWinner: {
            /** User Id */
            user_id: number;
            /** Username */
            username: string;
            /** Display Name */
            display_name?: string | null;
            /** Points Earned */
            points_earned: number;
            hits: components["schemas"]["VerdictHits"];
            /** Prev Rank */
            prev_rank?: number | null;
            /** New Rank */
            new_rank: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    signup_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_auth_auth_google_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleAuthRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoogleAuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    update_me_auth_me_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_new_league_leagues__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeagueCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeagueResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_league_leagues_preview__invite_code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invite_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_existing_league_leagues_join_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeagueJoin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeagueResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_leagues_leagues_my_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeagueResponse"][];
                };
            };
        };
    };
    get_leaderboard_leagues__league_id__leaderboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                league_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_league_match_predictions_leagues__league_id__matches__match_id__predictions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                league_id: number;
                match_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FriendPrediction"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_match_verdict_endpoint_leagues__league_id__matches__match_id__verdict_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                league_id: number;
                match_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DugoutEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_matches_matches__get: {
        parameters: {
            query?: {
                /** @description Filter by tournament ID */
                tournament_id?: number | null;
                /** @description Include completed matches */
                include_completed?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_match_detail_matches__match_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_players_for_match_matches__match_id__players_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchPlayersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_prediction_predictions__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PredictionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_predictions_predictions_my_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionResponse"][];
                };
            };
        };
    };
    get_my_predictions_detailed_predictions_my_detailed_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionDetailResponse"][];
                };
            };
        };
    };
    create_match_admin_matches__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_match_result_admin_matches__match_id__result_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchResultCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_matches_admin_matches_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_match_predictions_admin_matches__match_id__predictions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_match_squad_admin_matches__match_id__squad_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_match_lineup_admin_matches__match_id__lineup_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_match_lineup_admin_matches__match_id__lineup_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetLineupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_previous_lineup_admin_matches__match_id__previous_lineup_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    link_match_to_cricapi_admin_matches__match_id__link_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkMatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unlink_match_from_cricapi_admin_matches__match_id__link_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_match_sync_status_admin_matches__match_id__sync_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_manual_sync_admin_matches__match_id__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_mapping_admin_matches__match_id__player_mapping_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_player_mapping_admin_matches__match_id__player_mapping_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkPlayerMappingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_series_matches_admin_series__series_id__matches_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_picks_window_admin_tournaments__tournament_id__picks_window_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournament_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPicksWindowRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_picks_result_admin_tournaments__tournament_id__picks_result_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournament_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPicksResultRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vapid_public_key_notifications_vapid_public_key_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    subscribe_notifications_push_subscribe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushSubscribeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unsubscribe_notifications_push_subscribe_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushSubscribeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dugout_dugout__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DugoutEvent"][];
                };
            };
        };
    };
    dismiss_dugout_event_dugout_dismiss_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DugoutDismissRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tournaments_tournaments__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    get_my_picks_tournaments__tournament_id__picks_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournament_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TournamentPicksResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_picks_tournaments__tournament_id__picks_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournament_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TournamentPicksSubmit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TournamentPicksResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_teams_tournaments__tournament_id__teams_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournament_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamPickOption"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_players_tournaments__tournament_id__players_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournament_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerPickOption"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
