"""baseline

Revision ID: a1c99c58f11a
Revises: 
Create Date: 2026-05-13 14:17:45.958295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1c99c58f11a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=10), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('sport', sa.String(length=20), server_default='cricket', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('invite_code', sa.String(length=6), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=20), server_default='cricket', nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leagues_id'), 'leagues', ['id'], unique=False)
    op.create_index(op.f('ix_leagues_invite_code'), 'leagues', ['invite_code'], unique=True)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('cricapi_player_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cricapi_player_id')
    )
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=2048), nullable=False),
    sa.Column('auth', sa.String(length=512), nullable=False),
    sa.Column('p256dh', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_push_subscriptions_endpoint'), 'push_subscriptions', ['endpoint'], unique=True)
    op.create_index(op.f('ix_push_subscriptions_id'), 'push_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.create_table('dugout_dismissals',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('subject_username', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'type', 'league_id', 'match_id', 'subject_username')
    )
    op.create_table('league_members',
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prev_rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('league_id', 'user_id')
    )
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('sport', sa.String(length=20), server_default='cricket', nullable=False),
    sa.Column('picks_window', sa.String(length=10), server_default='closed', nullable=False),
    sa.Column('result_top4_team1_id', sa.Integer(), nullable=True),
    sa.Column('result_top4_team2_id', sa.Integer(), nullable=True),
    sa.Column('result_top4_team3_id', sa.Integer(), nullable=True),
    sa.Column('result_top4_team4_id', sa.Integer(), nullable=True),
    sa.Column('result_best_batsman_player_id', sa.Integer(), nullable=True),
    sa.Column('result_best_bowler_player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['result_best_batsman_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['result_best_bowler_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['result_top4_team1_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['result_top4_team2_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['result_top4_team3_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['result_top4_team4_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournaments_id'), 'tournaments', ['id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('team_1_id', sa.Integer(), nullable=False),
    sa.Column('team_2_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'COMPLETED', name='matchstatus'), nullable=False),
    sa.Column('external_match_id', sa.String(length=100), nullable=True),
    sa.Column('sync_state', sa.String(length=20), nullable=False),
    sa.Column('sync_error', sa.String(length=500), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('result_winner_id', sa.Integer(), nullable=True),
    sa.Column('result_most_runs_team1_player_id', sa.Integer(), nullable=True),
    sa.Column('result_most_runs_team2_player_id', sa.Integer(), nullable=True),
    sa.Column('result_most_wickets_team1_player_id', sa.Integer(), nullable=True),
    sa.Column('result_most_wickets_team2_player_id', sa.Integer(), nullable=True),
    sa.Column('result_pom_player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['result_most_runs_team1_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['result_most_runs_team2_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['result_most_wickets_team1_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['result_most_wickets_team2_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['result_pom_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['result_winner_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_1_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_2_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    op.create_table('tournament_picks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('top4_team1_id', sa.Integer(), nullable=True),
    sa.Column('top4_team2_id', sa.Integer(), nullable=True),
    sa.Column('top4_team3_id', sa.Integer(), nullable=True),
    sa.Column('top4_team4_id', sa.Integer(), nullable=True),
    sa.Column('best_batsman_player_id', sa.Integer(), nullable=True),
    sa.Column('best_bowler_player_id', sa.Integer(), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.Column('is_window2', sa.Boolean(), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['best_batsman_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['best_bowler_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['top4_team1_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['top4_team2_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['top4_team3_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['top4_team4_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tournament_id')
    )
    op.create_index(op.f('ix_tournament_picks_id'), 'tournament_picks', ['id'], unique=False)
    op.create_table('match_lineups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'player_id', name='uq_match_player')
    )
    op.create_index(op.f('ix_match_lineups_id'), 'match_lineups', ['id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('predicted_winner_id', sa.Integer(), nullable=False),
    sa.Column('predicted_most_runs_team1_player_id', sa.Integer(), nullable=False),
    sa.Column('predicted_most_runs_team2_player_id', sa.Integer(), nullable=False),
    sa.Column('predicted_most_wickets_team1_player_id', sa.Integer(), nullable=False),
    sa.Column('predicted_most_wickets_team2_player_id', sa.Integer(), nullable=False),
    sa.Column('predicted_pom_player_id', sa.Integer(), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['predicted_most_runs_team1_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['predicted_most_runs_team2_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['predicted_most_wickets_team1_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['predicted_most_wickets_team2_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['predicted_pom_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['predicted_winner_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_table('reminder_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_logs_id'), 'reminder_logs', ['id'], unique=False)
    op.create_index(op.f('ix_reminder_logs_match_id'), 'reminder_logs', ['match_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminder_logs_match_id'), table_name='reminder_logs')
    op.drop_index(op.f('ix_reminder_logs_id'), table_name='reminder_logs')
    op.drop_table('reminder_logs')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_match_lineups_id'), table_name='match_lineups')
    op.drop_table('match_lineups')
    op.drop_index(op.f('ix_tournament_picks_id'), table_name='tournament_picks')
    op.drop_table('tournament_picks')
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_tournaments_id'), table_name='tournaments')
    op.drop_table('tournaments')
    op.drop_table('league_members')
    op.drop_table('dugout_dismissals')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_index(op.f('ix_push_subscriptions_id'), table_name='push_subscriptions')
    op.drop_index(op.f('ix_push_subscriptions_endpoint'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_leagues_invite_code'), table_name='leagues')
    op.drop_index(op.f('ix_leagues_id'), table_name='leagues')
    op.drop_table('leagues')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
